services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    ports:
      - 5432:5432

  app:
    build: ./
    depends_on:
      postgresql:
        condition: service_healthy
    container_name: app
    restart: always
    env_file:
      - .env
    volumes:
      - ./src/:/src/
    ports:
      - 80:8000
    entrypoint: ["sh", "run.sh"]
