"""roles

Revision ID: dd48e7225997
Revises: 44280d0456ea
Create Date: 2024-02-10 22:15:19.776691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd48e7225997'
down_revision: Union[str, None] = '44280d0456ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.Enum('USER', 'ADMIN', name='rolenamechoice'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('pretty_name', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_roles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.execute("DROP type rolenamechoice;")
    # ### end Alembic commands ###
